import { Provider, WeeklySchedule } from '../../types/provider';
import { HomeProfile } from '../../types/home';
import { LifeInboxItem } from '../../types/inbox';
import { Task } from '../../types/task';
import { UserProfile } from '../../types/user';
import {
  ServiceCatalogItem,
  Booking,
  Quote,
  AuditEvent,
  OperationalNotification,
  Dispute,
  ChatMessage,
} from '../../types/marketplace';

const defaultWeeklySchedule: WeeklySchedule = {
  mon: { morning: true, afternoon: true, evening: true },
  tue: { morning: true, afternoon: true, evening: true },
  wed: { morning: true, afternoon: true, evening: true },
  thu: { morning: true, afternoon: true, evening: true },
  fri: { morning: true, afternoon: true, evening: true },
  sat: { morning: true, afternoon: true, evening: false },
  sun: { morning: false, afternoon: false, evening: false },
};

export const initialUser: UserProfile = {
  id: 'usr_nukri',
  firstName: 'ნუკრი',
  lastName: 'ჩაჩავა',
  email: 'nukrichachava9@gmail.com',
  phone: '+995 599 12 34 56',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  city: 'თბილისი',
  role: 'admin',
  status: 'verified',
  permissions: {
    canUseAI: true,
    canBookTasks: true,
    canViewCatalog: true,
    canAccessDecisionCenter: true,
    canAccessWallet: true,
    canAccessProviderPortal: true,
  },
  verifiedAt: '2026-08-01T10:00:00Z',
  verifiedBy: 'System',
  isBlocked: false,
  preferences: {
    preferredLanguage: 'ka',
    preferredTimeOfDay: 'evening',
    allowPhoneCalls: false, // prefers chat/silent
    priorityCriteria: 'highest_rated',
    savedAddresses: [
      {
        id: 'addr_home',
        label: 'ჩემი ბინა',
        district: 'ვაკე',
        addressLine: 'ი. ჭავჭავაძის გამზ. 37',
        notes: 'კოდი 124, მე-4 სართული',
      },
      {
        id: 'addr_office',
        label: 'ოფისი',
        district: 'საბურთალო',
        addressLine: 'ვაჟა-ფშაველას გამზ. 71',
      },
      {
        id: 'addr_parents',
        label: 'მშობლების სახლი',
        district: 'მთაწმინდა',
        addressLine: 'ლ. ასათიანის ქ. 12',
      },
    ],
    defaultAddressId: 'addr_home',
    favoriteProviderIds: ['p_giorgi_m', 'p_levan_s'],
  },
  createdAt: '2026-08-01T10:00:00Z',
  updatedAt: '2026-09-04T12:00:00Z',
};

export const seedUsers: UserProfile[] = [
  initialUser,
  {
    id: 'usr_giorgi',
    firstName: 'გიორგი',
    lastName: 'დოლიძე',
    email: 'giorgi.dolidze@gmail.com',
    phone: '+995 595 11 22 33',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    city: 'თბილისი',
    role: 'user',
    status: 'verified',
    permissions: {
      canUseAI: true,
      canBookTasks: true,
      canViewCatalog: true,
      canAccessDecisionCenter: true,
      canAccessWallet: true,
      canAccessProviderPortal: false,
    },
    verifiedAt: '2026-08-11T12:00:00Z',
    verifiedBy: 'ნუკრი ჩაჩავა',
    isBlocked: false,
    preferences: {
      preferredLanguage: 'ka',
      preferredTimeOfDay: 'morning',
      allowPhoneCalls: true,
      priorityCriteria: 'highest_rated',
      savedAddresses: [
        { id: 'addr_g1', label: 'ბინა (საბურთალო)', district: 'საბურთალო', addressLine: 'პეკინის გამზ. 18' }
      ],
      favoriteProviderIds: [],
    },
    createdAt: '2026-08-10T14:30:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'usr_nino_k',
    firstName: 'ნინო',
    lastName: 'კალანდაძე',
    email: 'nino.kalandadze@gmail.com',
    phone: '+995 577 44 55 66',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    city: 'თბილისი',
    role: 'user',
    status: 'pending_verification', // New unverified user
    permissions: {
      canUseAI: false,
      canBookTasks: false,
      canViewCatalog: true,
      canAccessDecisionCenter: false,
      canAccessWallet: false,
      canAccessProviderPortal: false,
    },
    isBlocked: false,
    preferences: {
      preferredLanguage: 'ka',
      preferredTimeOfDay: 'afternoon',
      allowPhoneCalls: true,
      priorityCriteria: 'best_value',
      savedAddresses: [
        { id: 'addr_n1', label: 'სახლი (ვერა)', district: 'ვერა', addressLine: 'ბარნოვის ქ. 45' }
      ],
      favoriteProviderIds: [],
    },
    createdAt: '2026-08-15T09:15:00Z',
    updatedAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'usr_alex_b',
    firstName: 'ალექსანდრე',
    lastName: 'ბერიძე',
    email: 'alex.beridze@gmail.com',
    phone: '+995 599 88 77 66',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    city: 'თბილისი',
    role: 'provider',
    status: 'verified',
    permissions: {
      canUseAI: true,
      canBookTasks: true,
      canViewCatalog: true,
      canAccessDecisionCenter: true,
      canAccessWallet: true,
      canAccessProviderPortal: true,
    },
    verifiedAt: '2026-08-06T10:00:00Z',
    verifiedBy: 'ნუკრი ჩაჩავა',
    isBlocked: false,
    preferences: {
      preferredLanguage: 'ka',
      preferredTimeOfDay: 'flexible',
      allowPhoneCalls: true,
      priorityCriteria: 'fastest_arrival',
      savedAddresses: [],
      favoriteProviderIds: [],
    },
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'usr_salome_j',
    firstName: 'სალომე',
    lastName: 'ჯაფარიძე',
    email: 'salome.j@gmail.com',
    phone: '+995 591 33 22 11',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    city: 'თბილისი',
    role: 'user',
    status: 'pending_verification', // New unverified user
    permissions: {
      canUseAI: false,
      canBookTasks: false,
      canViewCatalog: true,
      canAccessDecisionCenter: false,
      canAccessWallet: false,
      canAccessProviderPortal: false,
    },
    isBlocked: false,
    preferences: {
      preferredLanguage: 'ka',
      preferredTimeOfDay: 'evening',
      allowPhoneCalls: false,
      priorityCriteria: 'highest_rated',
      savedAddresses: [],
      favoriteProviderIds: [],
    },
    createdAt: '2026-08-20T18:00:00Z',
    updatedAt: '2026-09-04T09:00:00Z',
  },
];

export const seedProviders: Provider[] = [
  // 1. Plumbing - Giorgi (Top Recommendation)
  {
    id: 'prov_giorgi_plumb',
    name: 'გიორგი მახარაძე',
    nameKa: 'გიორგი მახარაძე',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+995 577 11 22 33',
    categories: ['plumbing'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'ბაგები'],
    rating: 4.95,
    reviewCount: 142,
    completedJobs: 128,
    verificationBadge: 'verified',
    verificationStatus: 'verified',
    verificationDate: '2026-01-15',
    documentsStatus: 'approved',
    completionRate: 98.4,
    cancellationRate: 1.2,
    responseTimeMinutes: 3,
    pricingModel: 'price_range',
    availability: 'available',
    estimatedArrivalMinutes: 35,
    pricing: {
      min: 60,
      max: 85,
      baseCalloutFee: 30,
      unit: 'სამუშაოზე',
    },
    languages: ['ქართული', 'English'],
    bio: 'სანტექნიკის ექსპერტი 12 წლიანი გამოცდილებით. წყლის გაჟონვა, მილების მონტაჟი, შემრევების შეცვლა.',
    bioKa: 'სანტექნიკის ექსპერტი 12 წლიანი გამოცდილებით. წყლის გაჟონვა, მილების მონტაჟი, შემრევების შეცვლა.',
    specialties: ['წყლის გაჟონვა', 'მილების დიაგნოსტიკა', 'შემრევი ონკანები'],
    specialtiesKa: ['წყლის გაჟონვა', 'მილების დიაგნოსტიკა', 'შემრევი ონკანები'],
    completedSimilarTasksCount: 38,
    matchScore: 96,
    matchReasons: [
      'სასურველ უბანში (ვაკე) მუშაობს',
      'სასურველ დროს თავისუფალია',
      'მაღალი შეფასება აქვს (4.95 ★)',
      '38 მსგავსი საქმე შესრულებული',
    ],
    matchRationaleKa: 'გირჩევ იმიტომ, რომ მსგავსი პრობლემები 38-ჯერ აქვს შესრულებული და დღესვე შეუძლია მოსვლა.',
    matchRationaleEn: 'Recommended because he has solved similar leak issues 38 times and is available today.',
    isFavorite: true,
    schedule: defaultWeeklySchedule,
  },
  // 2. Plumbing - Davit
  {
    id: 'prov_davit_plumb',
    name: 'დავით კაპანაძე',
    nameKa: 'დავით კაპანაძე',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+995 593 44 55 66',
    categories: ['plumbing'],
    serviceAreas: ['საბურთალო', 'დიღომი', 'დიდუბე', 'ვაკე'],
    rating: 4.88,
    reviewCount: 89,
    completedJobs: 95,
    verificationBadge: 'top_provider',
    verificationStatus: 'verified',
    verificationDate: '2026-02-10',
    documentsStatus: 'approved',
    completionRate: 97.0,
    cancellationRate: 2.1,
    responseTimeMinutes: 6,
    pricingModel: 'starting_from',
    availability: 'available',
    estimatedArrivalMinutes: 50,
    pricing: {
      min: 55,
      max: 80,
      baseCalloutFee: 25,
      unit: 'სამუშაოზე',
    },
    languages: ['ქართული'],
    bio: 'სწრაფი და ხარისხიანი სანტექნიკური მომსახურება.',
    bioKa: 'სწრაფი და ხარისხიანი სანტექნიკური მომსახურება.',
    specialties: ['წყლის წნევის რეგულირება', 'მილგაყვანილობა'],
    specialtiesKa: ['წყლის წნევის რეგულირება', 'მილგაყვანილობა'],
    completedSimilarTasksCount: 22,
    matchScore: 88,
    matchReasons: [
      'საბურთალოსა და ვაკეში მუშაობს',
      'ხელმისაწვდომი ფასი (55 ₾-დან)',
    ],
    matchRationaleKa: 'მაღალი რეიტინგი და ხელმისაწვდომი ფასი საბურთალოსა და ვაკეში.',
    matchRationaleEn: 'High rating and competitive pricing in Saburtalo and Vake.',
    schedule: defaultWeeklySchedule,
  },
  // 3. Cleaning - Nino (Top Cleaner)
  {
    id: 'prov_nino_clean',
    name: 'ნინო ბერიძე',
    nameKa: 'ნინო ბერიძე',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+995 555 77 88 99',
    categories: ['cleaning'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა'],
    rating: 4.98,
    reviewCount: 194,
    completedJobs: 215,
    verificationBadge: 'verified',
    verificationStatus: 'verified',
    verificationDate: '2025-11-20',
    documentsStatus: 'approved',
    completionRate: 99.1,
    cancellationRate: 0.5,
    responseTimeMinutes: 2,
    pricingModel: 'price_range',
    availability: 'available',
    estimatedArrivalMinutes: 45,
    pricing: {
      min: 80,
      max: 120,
      baseCalloutFee: 0,
      unit: 'ბინის დალაგება',
    },
    languages: ['ქართული', 'English', 'Russian'],
    bio: 'პროფესიონალური ეკო-დასუფთავება გერმანული ჰიპოალერგიული საშუალებებით.',
    bioKa: 'პროფესიონალური ეკო-დასუფთავება გერმანული ჰიპოალერგიული საშუალებებით.',
    specialties: ['გენერალური დასუფთავება', 'ეკო-ქიმია', 'ფანჯრების წმენდა'],
    specialtiesKa: ['გენერალური დასუფთავება', 'ეკო-ქიმია', 'ფანჯრების წმენდა'],
    completedSimilarTasksCount: 64,
    matchScore: 98,
    matchReasons: [
      'შენი რჩეული პროვაიდერი',
      'უმაღლესი რეიტინგი (4.98 ★)',
      'სასურველ დროს თავისუფალია',
      '64 მსგავსი საქმე შესრულებული',
    ],
    matchRationaleKa: 'ემთხვევა შენს წინა არჩევანს, აქვს 4.98 რეიტინგი და იყენებს ეკო-საშუალებებს.',
    matchRationaleEn: 'Matches your previous preference, 4.98 rating, uses premium eco products.',
    isFavorite: true,
    schedule: defaultWeeklySchedule,
  },
  // 4. Cleaning - Mariam
  {
    id: 'prov_mariam_clean',
    name: 'მარიამ ჯავახიშვილი',
    nameKa: 'მარიამ ჯავახიშვილი',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+995 598 33 22 11',
    categories: ['cleaning'],
    serviceAreas: ['დიდუბე', 'ისანი', 'ავლაბარი', 'ჩუღურეთი'],
    rating: 4.86,
    reviewCount: 76,
    completedJobs: 82,
    verificationBadge: 'fast_response',
    verificationStatus: 'verified',
    verificationDate: '2026-03-01',
    documentsStatus: 'approved',
    completionRate: 96.5,
    cancellationRate: 2.5,
    responseTimeMinutes: 5,
    pricingModel: 'fixed',
    availability: 'available',
    estimatedArrivalMinutes: 30,
    pricing: {
      min: 70,
      max: 100,
      baseCalloutFee: 0,
      unit: 'ბინის დალაგება',
    },
    languages: ['ქართული'],
    bio: 'სწრაფი და გულმოდგინე საოჯახო დალაგება.',
    bioKa: 'სწრაფი და გულმოდგინე საოჯახო დალაგება.',
    specialties: ['სტანდარტული დალაგება', 'სამზარეულოს გაწმენდა'],
    specialtiesKa: ['სტანდარტული დალაგება', 'სამზარეულოს გაწმენდა'],
    completedSimilarTasksCount: 19,
    matchScore: 84,
    matchReasons: [
      'სწრაფი რეაგირება (~5 წთ)',
      'ფიქსირებული ბიუჯეტური ფასი (70 ₾)',
    ],
    matchRationaleKa: 'სწრაფი რეაგირება და ბიუჯეტური ფასი.',
    matchRationaleEn: 'Fast response and value pricing.',
    schedule: defaultWeeklySchedule,
  },
  // 5. AC / Heating - Levan (Top AC Specialist)
  {
    id: 'prov_levan_ac',
    name: 'ლევან წიკლაური',
    nameKa: 'ლევან წიკლაური',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    phone: '+995 599 33 44 55',
    categories: ['ac_heating'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'დიღომი', 'გლდანი', 'მთაწმინდა'],
    rating: 4.96,
    reviewCount: 168,
    completedJobs: 174,
    verificationBadge: 'verified',
    verificationStatus: 'verified',
    verificationDate: '2025-10-05',
    documentsStatus: 'approved',
    completionRate: 98.8,
    cancellationRate: 1.0,
    responseTimeMinutes: 4,
    pricingModel: 'price_range',
    availability: 'available',
    estimatedArrivalMinutes: 40,
    pricing: {
      min: 70,
      max: 110,
      baseCalloutFee: 30,
      unit: 'შემოწმება/წმენდა',
    },
    languages: ['ქართული', 'English'],
    bio: 'კლიმატური სისტემების სერტიფიცირებული ინჟინერი (Daikin, Midea, Samsung). ფრეონის დატუმბვა, ანტიბაქტერიული წმენდა.',
    bioKa: 'კლიმატური სისტემების სერტიფიცირებული ინჟინერი (Daikin, Midea, Samsung). ფრეონის დატუმბვა, ანტიბაქტერიული წმენდა.',
    specialties: ['ანტიბაქტერიული წმენდა', 'ფრეონით შევსება', 'გათბობის ქვაბი'],
    specialtiesKa: ['ანტიბაქტერიული წმენდა', 'ფრეონით შევსება', 'გათბობის ქვაბი'],
    completedSimilarTasksCount: 52,
    matchScore: 97,
    matchReasons: [
      'სასურველ უბანში (ვაკე) მუშაობს',
      'სერტიფიცირებული ინჟინერი (Daikin/Samsung)',
      'მაღალი რეიტინგი (4.96 ★)',
      '52 მსგავსი საქმე შესრულებული',
    ],
    matchRationaleKa: 'სერტიფიცირებული ინჟინერი, ანტიბაქტერიული ორთქლის აპარატით და 52 მსგავსი სამუშაოთი.',
    matchRationaleEn: 'Certified AC engineer with antibacterial steam gear and 52 similar jobs.',
    schedule: defaultWeeklySchedule,
  },
  // 6. AC / Heating - Irakli
  {
    id: 'prov_irakli_ac',
    name: 'ირაკლი კვარაცხელია',
    nameKa: 'ირაკლი კვარაცხელია',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    phone: '+995 577 88 99 00',
    categories: ['ac_heating'],
    serviceAreas: ['საბურთალო', 'ნუცუბიძე', 'დიდუბე'],
    rating: 4.89,
    reviewCount: 92,
    completedJobs: 88,
    verificationBadge: 'top_provider',
    verificationStatus: 'verified',
    verificationDate: '2026-02-18',
    documentsStatus: 'approved',
    completionRate: 96.0,
    cancellationRate: 2.0,
    responseTimeMinutes: 7,
    pricingModel: 'quote_required',
    availability: 'available',
    estimatedArrivalMinutes: 60,
    pricing: {
      min: 65,
      max: 95,
      baseCalloutFee: 25,
      unit: 'შემოწმება',
    },
    languages: ['ქართული'],
    bio: 'კონდიციონერების მონტაჟი და შეკეთება.',
    bioKa: 'კონდიციონერების მონტაჟი და შეკეთება.',
    specialties: ['კონდიციონერის დიაგნოსტიკა', 'ფილტრების რეცხვა'],
    specialtiesKa: ['კონდიციონერის დიაგნოსტიკა', 'ფილტრების რეცხვა'],
    completedSimilarTasksCount: 31,
    matchScore: 89,
    matchReasons: [
      'საბურთალოს ტერიტორიაზე მუშაობს',
      'ფასი შეთანხმებით დიაგნოსტიკის შემდეგ',
    ],
    matchRationaleKa: 'საიმედო ტექნიკოსი კარგი რეიტინგით საბურთალოს ტერიტორიაზე.',
    matchRationaleEn: 'Reliable technician with strong track record in Saburtalo.',
    schedule: defaultWeeklySchedule,
  },
  // 7. Electrician - Zurab
  {
    id: 'prov_zurab_elec',
    name: 'ზურაბ გელოვანი',
    nameKa: 'ზურაბ გელოვანი',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    phone: '+995 595 11 22 44',
    categories: ['electrician'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიდუბე'],
    rating: 4.97,
    reviewCount: 156,
    completedJobs: 160,
    verificationBadge: 'verified',
    verificationStatus: 'verified',
    verificationDate: '2025-12-10',
    documentsStatus: 'approved',
    completionRate: 99.0,
    cancellationRate: 0.8,
    responseTimeMinutes: 3,
    pricingModel: 'price_range',
    availability: 'available',
    estimatedArrivalMinutes: 30,
    pricing: {
      min: 50,
      max: 90,
      baseCalloutFee: 25,
      unit: 'სამუშაოზე',
    },
    languages: ['ქართული', 'English'],
    bio: 'უმაღლესი კატეგორიის ელექტრიკოსი. მოკლე ჩართვების აღმოფხვრა, ავტომატების შეცვლა, ჭაღების მონტაჟი.',
    bioKa: 'უმაღლესი კატეგორიის ელექტრიკოსი. მოკლე ჩართვების აღმოფხვრა, ავტომატების შეცვლა, ჭაღების მონტაჟი.',
    specialties: ['მოკლე ჩართვის დიაგნოსტიკა', 'ფარის აწყობა', 'LED განათება'],
    specialtiesKa: ['მოკლე ჩართვის დიაგნოსტიკა', 'ფარის აწყობა', 'LED განათება'],
    completedSimilarTasksCount: 44,
    matchScore: 95,
    matchReasons: [
      'სასურველ უბანში (ვაკე) მუშაობს',
      'სწრაფი რეაგირება (~3 წთ)',
      '44 მსგავსი საქმე შესრულებული',
    ],
    matchRationaleKa: 'უმაღლესი კვალიფიკაცია ელექტრო უსაფრთხოებაში და სწრაფი მოსვლა.',
    matchRationaleEn: 'Top certified electrical safety expert with rapid arrival.',
    schedule: defaultWeeklySchedule,
  },
  // 8. Courier / Errands - Salome
  {
    id: 'prov_salome_courier',
    name: 'სალომე ჩხიკვაძე',
    nameKa: 'სალომე ჩხიკვაძე',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+995 599 88 77 66',
    categories: ['courier'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიდუბე', 'ისანი'],
    rating: 4.99,
    reviewCount: 220,
    completedJobs: 240,
    verificationBadge: 'verified',
    verificationStatus: 'verified',
    verificationDate: '2025-09-12',
    documentsStatus: 'approved',
    completionRate: 99.5,
    cancellationRate: 0.2,
    responseTimeMinutes: 2,
    pricingModel: 'fixed',
    availability: 'available',
    estimatedArrivalMinutes: 20,
    pricing: {
      min: 25,
      max: 45,
      baseCalloutFee: 15,
      unit: 'გაგზავნაზე',
    },
    languages: ['ქართული', 'English'],
    bio: 'სწრაფი ექსპრეს კურიერი და პირადი დამხმარე თბილისში. დოკუმენტები, საყიდლები, გასაღების მიტანა.',
    bioKa: 'სწრაფი ექსპრეს კურიერი და პირადი დამხმარე თბილისში. დოკუმენტები, საყიდლები, გასაღების მიტანა.',
    specialties: ['ექსპრეს მიტანა', 'დოკუმენტების გადაცემა', 'მარკეტიდან მოტანა'],
    specialtiesKa: ['ექსპრეს მიტანა', 'დოკუმენტების გადაცემა', 'მარკეტიდან მოტანა'],
    completedSimilarTasksCount: 88,
    matchScore: 99,
    matchReasons: [
      '20 წუთში შეუძლია აღება',
      'უმაღლესი რეიტინგი 4.99 ★',
      '88 შესრულებული ექსპრეს დავალება',
    ],
    matchRationaleKa: '20 წუთში შეუძლია აღება, უმაღლესი სანდოობის რეიტინგი 4.99.',
    matchRationaleEn: 'Can pickup in 20 min with highest reliability rating of 4.99.',
    schedule: defaultWeeklySchedule,
  },
  // 9. Mobile Car Wash - Bata
  {
    id: 'prov_bata_carwash',
    name: 'ბათა კვარაცხელია',
    nameKa: 'ბათა კვარაცხელია',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+995 597 12 34 89',
    categories: ['car_wash'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'ბაგები'],
    rating: 4.92,
    reviewCount: 118,
    completedJobs: 134,
    verificationBadge: 'verified',
    verificationStatus: 'verified',
    verificationDate: '2026-01-20',
    documentsStatus: 'approved',
    completionRate: 98.2,
    cancellationRate: 1.1,
    responseTimeMinutes: 4,
    pricingModel: 'starting_from',
    availability: 'available',
    estimatedArrivalMinutes: 35,
    pricing: {
      min: 30,
      max: 45,
      baseCalloutFee: 0,
      unit: 'მობილური რეცხვა',
    },
    languages: ['ქართული', 'English'],
    bio: 'მობილური ეკო-დითეილინგი და რეცხვა ადგილზე მოსვლით. ორთქლის აპარატი, პრემიუმ შამპუნები.',
    bioKa: 'მობილური ეკო-დითეილინგი და რეცხვა ადგილზე მოსვლით. ორთქლის აპარატი, პრემიუმ შამპუნები.',
    specialties: ['მობილური რეცხვა', 'სალონის ორთქლით წმენდა', 'ჰიდროფობული დამცავი'],
    specialtiesKa: ['მობილური რეცხვა', 'სალონის ორთქლით წმენდა', 'ჰიდროფობული დამცავი'],
    completedSimilarTasksCount: 42,
    matchScore: 94,
    matchReasons: [
      'ადგილზე მოდის ორთქლის აპარატურით',
      'ვაკე-საბურთალოს უბნებში მუშაობს',
    ],
    matchRationaleKa: 'ადგილზე მოდის ორთქლის აპარატურით, უმაღლესი შეფასება აქვს ვაკე-საბურთალოში.',
    matchRationaleEn: 'Comes on-site with steam detailing, top ratings in Vake and Saburtalo.',
    schedule: defaultWeeklySchedule,
  },
  // 10. Mobile Car Wash - Sandro
  {
    id: 'prov_sandro_carwash',
    name: 'სანდრო თოდუა',
    nameKa: 'სანდრო თოდუა',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    phone: '+995 591 99 88 77',
    categories: ['car_wash'],
    serviceAreas: ['საბურთალო', 'დიღომი', 'დიდუბე'],
    rating: 4.85,
    reviewCount: 65,
    completedJobs: 71,
    verificationBadge: 'fast_response',
    verificationStatus: 'verified',
    verificationDate: '2026-03-05',
    documentsStatus: 'approved',
    completionRate: 96.0,
    cancellationRate: 2.2,
    responseTimeMinutes: 5,
    pricingModel: 'fixed',
    availability: 'available',
    estimatedArrivalMinutes: 45,
    pricing: {
      min: 25,
      max: 40,
      baseCalloutFee: 0,
      unit: 'მობილური რეცხვა',
    },
    languages: ['ქართული'],
    bio: 'სწრაფი ექსპრეს რეცხვა და სალონის მოწესრიგება.',
    bioKa: 'სწრაფი ექსპრეს რეცხვა და სალონის მოწესრიგება.',
    specialties: ['ექსპრეს რეცხვა', 'სალონის მტვერსასრუტი'],
    specialtiesKa: ['ექსპრეს რეცხვა', 'სალონის მტვერსასრუტი'],
    completedSimilarTasksCount: 20,
    matchScore: 86,
    matchReasons: [
      'ხელმისაწვდომი ფიქსირებული ფასი (25 ₾)',
      'სწრაფი მოსვლა',
    ],
    matchRationaleKa: 'ხელმისაწვდომი ფასი და სწრაფი მოსვლა.',
    matchRationaleEn: 'Affordable pricing and rapid arrival.',
    schedule: defaultWeeklySchedule,
  },
];

// Structured Service Catalog Items
export const seedServices: ServiceCatalogItem[] = [
  {
    id: 'srv_deep_clean',
    name: 'Deep Apartment Cleaning',
    nameKa: 'ბინის გენერალური დალაგება',
    category: 'cleaning',
    description: 'Complete deep cleaning of all rooms, kitchen degreasing, bathroom descaling.',
    descriptionKa: 'ყველა ოთახის გენერალური დასუფთავება, სამზარეულოს ცხიმგაცლა, სველი წერტილების დეზინფექცია.',
    pricingModel: 'price_range',
    priceRange: { min: 80, max: 130 },
    durationHours: 3.5,
    requiredInfo: ['ოთახების რაოდენობა', 'ფართობი (კვ.მ)', 'ცხოველები სახლში'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიდუბე'],
    availabilityNoteKa: 'ხელმისაწვდომია ყოველდღე 09:00-20:00',
  },
  {
    id: 'srv_window_clean',
    name: 'Window & Glass Wash',
    nameKa: 'ფანჯრებისა და ვიტრაჟების წმენდა',
    category: 'cleaning',
    description: 'Double-sided glass cleaning, tracks and frame wash.',
    descriptionKa: 'ორმხრივი წმენდა, რაფებისა და ჩარჩოების მოწესრიგება უსაფრთხოების ნორმების დაცვით.',
    pricingModel: 'fixed',
    basePrice: 50,
    durationHours: 1.5,
    requiredInfo: ['ფანჯრების რაოდენობა', 'სართული'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა'],
    availabilityNoteKa: 'ხელმისაწვდომია დღის სინათლეზე',
  },
  {
    id: 'srv_leak_repair',
    name: 'Emergency Pipe Leak Repair',
    nameKa: 'წყლის გაჟონვის ლიკვიდაცია',
    category: 'plumbing',
    description: 'Urgent leak diagnostics, joint tightening, pipe repair.',
    descriptionKa: 'გადაუდებელი დიაგნოსტიკა, მილების შეერთებების გამკვრივება, დაზიანებული ნაწილის შეცვლა.',
    pricingModel: 'starting_from',
    basePrice: 60,
    priceRange: { min: 60, max: 95 },
    durationHours: 1.5,
    requiredInfo: ['გაჟონვის ლოკაცია', 'წყლის გადაკეტვის შესაძლებლობა'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიდუბე', 'ისანი'],
    availabilityNoteKa: 'ექსპრეს რეაგირება 35 წუთში',
  },
  {
    id: 'srv_faucet_install',
    name: 'Faucet & Mixer Replacement',
    nameKa: 'შემრევი ონკანის მონტაჟი',
    category: 'plumbing',
    description: 'Disassembly of old mixer and leak-free installation of new faucet.',
    descriptionKa: 'ძველი ონკანის დემონტაჟი და ახლის ჰერმეტული მონტაჟი გარანტიით.',
    pricingModel: 'fixed',
    basePrice: 45,
    durationHours: 1.0,
    requiredInfo: ['ახალი ონკანი ნაყიდია თუ არა'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'დიღომი', 'დიდუბე'],
    availabilityNoteKa: 'დღესვე შესაძლებელია',
  },
  {
    id: 'srv_ac_antibacterial',
    name: 'AC Antibacterial Steam Clean',
    nameKa: 'კონდიციონერის ანტიბაქტერიული წმენდა',
    category: 'ac_heating',
    description: 'Steam disinfection of filters, heat exchanger, and condensate drainage.',
    descriptionKa: 'ფილტრებისა და რადიატორის ღრმა ორთქლით წმენდა, სოკოს საწინააღმდეგო დამუშავება.',
    pricingModel: 'fixed',
    basePrice: 70,
    durationHours: 1.0,
    requiredInfo: ['კონდიციონერის მოდელი/სიმძლავრე'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიღომი'],
    availabilityNoteKa: 'სეზონური მომსახურება',
  },
  {
    id: 'srv_ac_freon',
    name: 'Freon Gas Recharge & Diagnostics',
    nameKa: 'ფრეონით შევსება და დიაგნოსტიკა',
    category: 'ac_heating',
    description: 'Pressure leak test and certified R410A / R32 refrigerant top-up.',
    descriptionKa: 'წნევის შემოწმება, გაჟონვის ტესტი და სერტიფიცირებული ფრეონით (R410A/R32) შევსება.',
    pricingModel: 'quote_required',
    priceRange: { min: 80, max: 130 },
    durationHours: 1.5,
    requiredInfo: ['არ აგრილებს თუ საერთოდ არ ირთვება'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'დიღომი', 'გლდანი'],
    availabilityNoteKa: 'ოსტატის შეფასებით სამუშაოზე',
  },
  {
    id: 'srv_elec_short_circuit',
    name: 'Short Circuit & Fuse Diagnostics',
    nameKa: 'მოკლე ჩართვის დიაგნოსტიკა & შეკეთება',
    category: 'electrician',
    description: 'Thermal inspection of electrical board, breaker troubleshooting.',
    descriptionKa: 'ელექტრო ფარის თერმოგრაფიული შემოწმება, ამომრთველების შეცვლა, უსაფრთხოების აღდგენა.',
    pricingModel: 'starting_from',
    basePrice: 50,
    durationHours: 1.5,
    requiredInfo: ['მთლიან სახლში გაითიშა შუქი თუ კონკრეტულ ოთახში'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიდუბე'],
    availabilityNoteKa: 'გადაუდებელი უსაფრთხოების სერვისი',
  },
  {
    id: 'srv_courier_urgent',
    name: 'Express City Courier',
    nameKa: 'სწრაფი ექსპრეს კურიერი',
    category: 'courier',
    description: 'Point-to-point secure delivery of documents, keys, or parcels within 60 mins.',
    descriptionKa: 'წერილების, გასაღების ან ამანათის უსაფრთხო მიტანა თბილისის მასშტაბით 60 წუთში.',
    pricingModel: 'fixed',
    basePrice: 25,
    durationHours: 0.8,
    requiredInfo: ['აღების მისამართი', 'ჩაბარების მისამართი', 'ტვირთის ზომა'],
    serviceAreas: ['ვაკე', 'საბურთალო', 'ვერა', 'მთაწმინდა', 'დიდუბე', 'ისანი'],
    availabilityNoteKa: '20 წუთში აღება',
  },
];

// Seed Real Operational Bookings
export const seedBookings: Booking[] = [
  {
    bookingId: 'bk_2026_ac_01',
    taskId: 'task_active_ac',
    userId: 'usr_nukri',
    providerId: 'prov_levan_ac',
    providerName: 'ლევან წიკლაური',
    providerNameKa: 'ლევან წიკლაური',
    providerAvatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    providerPhone: '+995 599 33 44 55',
    serviceId: 'srv_ac_antibacterial',
    serviceTitleKa: 'კონდიციონერის შემოწმება & წმენდა',
    category: 'ac_heating',
    scheduledStart: 'დღეს · 18:30',
    scheduledEnd: 'დღეს · 19:30',
    location: 'ი. ჭავჭავაძის გამზ. 37, ვაკე',
    addressLabel: 'ჩემი ბინა',
    price: 90,
    pricingModel: 'price_range',
    paymentStatus: 'authorized',
    bookingStatus: 'provider_on_way',
    notes: 'კოდი 124, მე-4 სართული. კონდიციონერი მისაღებშია.',
    createdAt: '2026-09-04T13:16:00Z',
    updatedAt: '2026-09-04T13:55:00Z',
  },
  {
    bookingId: 'bk_2026_clean_02',
    taskId: 'task_active_clean',
    userId: 'usr_nukri',
    providerId: 'prov_nino_clean',
    providerName: 'ნინო ბერიძე',
    providerNameKa: 'ნინო ბერიძე',
    providerAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    providerPhone: '+995 555 77 88 99',
    serviceId: 'srv_deep_clean',
    serviceTitleKa: 'ბინის დალაგება (ეკო-საშუალებები)',
    category: 'cleaning',
    scheduledStart: 'ხვალ · 11:00',
    scheduledEnd: 'ხვალ · 14:00',
    location: 'ი. ჭავჭავაძის გამზ. 37, ვაკე',
    addressLabel: 'ჩემი ბინა',
    price: 95,
    pricingModel: 'price_range',
    paymentStatus: 'authorization_required',
    bookingStatus: 'confirmed',
    notes: 'ეკო-საშუალებებით, ფანჯრებიც გაიწმინდოს.',
    createdAt: '2026-09-04T10:20:00Z',
    updatedAt: '2026-09-04T10:20:00Z',
  },
  {
    bookingId: 'bk_2026_courier_03',
    taskId: 'task_done_courier',
    userId: 'usr_nukri',
    providerId: 'prov_salome_courier',
    providerName: 'სალომე ჩხიკვაძე',
    providerNameKa: 'სალომე ჩხიკვაძე',
    providerAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    providerPhone: '+995 599 88 77 66',
    serviceId: 'srv_courier_urgent',
    serviceTitleKa: 'ხელშეკრულების გადაცემა ნოტარიუსთან',
    category: 'courier',
    scheduledStart: 'დღეს · 11:00',
    scheduledEnd: 'დღეს · 11:45',
    location: 'რუსთაველის გამზ. 24',
    addressLabel: 'სამსახური',
    price: 25,
    pricingModel: 'fixed',
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    notes: 'ხელშეკრულება წარმატებით ჩაბარდა ნოტარიუსს.',
    createdAt: '2026-09-04T07:15:00Z',
    updatedAt: '2026-09-04T08:15:00Z',
  },
];

// Seed Quotes for Negotiation Flow
export const seedQuotes: Quote[] = [
  {
    id: 'quote_ac_irakli',
    taskId: 'task_active_ac',
    providerId: 'prov_irakli_ac',
    providerName: 'ირაკლი კვარაცხელია',
    providerNameKa: 'ირაკლი კვარაცხელია',
    providerAvatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    serviceTitleKa: 'კონდიციონერის შემოწმება & ფრეონის დიაგნოსტიკა',
    price: 85,
    pricingModel: 'quote',
    expectedDurationHours: 1.0,
    expiresAt: '24 სთ განმავლობაში',
    notesKa: 'ფასში შედის პირველადი წნევის ტესტი და ფილტრების გარეცხვა.',
    status: 'pending',
    createdAt: '2026-09-04T13:20:00Z',
  },
  {
    id: 'quote_plumb_davit',
    taskId: 'task_leak_sample',
    providerId: 'prov_davit_plumb',
    providerName: 'დავით კაპანაძე',
    providerNameKa: 'დავით კაპანაძე',
    providerAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    serviceTitleKa: 'მილის გაჟონვის შეკეთება ახალი შეერთებით',
    price: 65,
    pricingModel: 'quote',
    expectedDurationHours: 1.5,
    expiresAt: '24 სთ განმავლობაში',
    notesKa: 'ახალი პლასტმასის მუხლი და საიზოლაციო ლენტა შედის.',
    status: 'pending',
    createdAt: '2026-09-04T11:00:00Z',
  },
];

// Seed Contextual Chat Messages
export const seedChatMessages: ChatMessage[] = [
  {
    id: 'msg_1',
    bookingId: 'bk_2026_ac_01',
    senderId: 'usr_nukri',
    senderRole: 'user',
    senderName: 'ნუკრი',
    text: 'გამარჯობა ლევან, სადარბაზოს კოდია 124. ლიფტი მუშაობს.',
    createdAt: '2026-09-04T13:25:00Z',
    quickAction: 'მისამართის გაგზავნა',
  },
  {
    id: 'msg_2',
    bookingId: 'bk_2026_ac_01',
    senderId: 'prov_levan_ac',
    senderRole: 'provider',
    senderName: 'ლევან წიკლაური',
    text: 'გამარჯობა! მადლობა, გასაგებია. ორთქლის აპარატით მოვდივარ, 18:30-ზე ადგილზე ვიქნები.',
    createdAt: '2026-09-04T13:28:00Z',
  },
  {
    id: 'msg_3',
    bookingId: 'bk_2026_ac_01',
    senderId: 'prov_levan_ac',
    senderRole: 'provider',
    senderName: 'ლევან წიკლაური',
    text: 'ახლა გზაში ვარ ჭავჭავაძისკენ.',
    createdAt: '2026-09-04T13:55:00Z',
  },
];

// Seed Disputes
export const seedDisputes: Dispute[] = [
  {
    id: 'disp_sample_01',
    bookingId: 'bk_2026_courier_03',
    userId: 'usr_nukri',
    userName: 'ნუკრი ჩაჩავა',
    providerId: 'prov_salome_courier',
    providerName: 'სალომე ჩხიკვაძე',
    reason: 'other',
    reasonKa: 'დაზუსტება ქვითარზე',
    description: 'ქვითრის ელექტრონული ასლი დამჭირდა ბუღალტერიისთვის.',
    status: 'resolved',
    resolutionNotesKa: 'ქვითარი გაგზავნილია მეილზე. საკითხი მოგვარებულია.',
    createdAt: '2026-09-04T08:30:00Z',
    updatedAt: '2026-09-04T08:45:00Z',
  },
];

// Seed Audit Events for Transparency
export const seedAuditEvents: AuditEvent[] = [
  {
    id: 'aud_1',
    eventType: 'task.created',
    entityId: 'task_active_ac',
    actorId: 'usr_nukri',
    actorRole: 'user',
    actorName: 'ნუკრი ჩაჩავა',
    timestamp: '2026-09-04T13:15:00Z',
    detailsKa: 'მომხმარებელმა შექმნა დავალება: "კონდიციონერის შემოწმება"',
  },
  {
    id: 'aud_2',
    eventType: 'provider.matched',
    entityId: 'prov_levan_ac',
    actorId: 'system',
    actorRole: 'system',
    actorName: 'DOXO Matching Engine',
    timestamp: '2026-09-04T13:15:05Z',
    detailsKa: 'ლევან წიკლაურს მიენიჭა 97% შესაბამისობა (ვაკე, ხელმისაწვდომი)',
  },
  {
    id: 'aud_3',
    eventType: 'booking.created',
    entityId: 'bk_2026_ac_01',
    actorId: 'usr_nukri',
    actorRole: 'user',
    actorName: 'ნუკრი ჩაჩავა',
    timestamp: '2026-09-04T13:16:00Z',
    detailsKa: 'შეიქმნა ჯავშანი: ლევან წიკლაური, დღეს 18:30, 90 ₾',
  },
  {
    id: 'aud_4',
    eventType: 'booking.confirmed',
    entityId: 'bk_2026_ac_01',
    actorId: 'prov_levan_ac',
    actorRole: 'provider',
    actorName: 'ლევან წიკლაური',
    timestamp: '2026-09-04T13:17:00Z',
    detailsKa: 'პროვაიდერმა დაადასტურა ვიზიტი',
  },
  {
    id: 'aud_5',
    eventType: 'provider.on_way',
    entityId: 'bk_2026_ac_01',
    actorId: 'prov_levan_ac',
    actorRole: 'provider',
    actorName: 'ლევან წიკლაური',
    timestamp: '2026-09-04T13:55:00Z',
    detailsKa: 'პროვაიდერი დაიძრა მისამართზე (ი. ჭავჭავაძის 37)',
  },
];

// Seed Operational Notifications
export const seedNotifications: OperationalNotification[] = [
  {
    id: 'notif_1',
    targetRole: 'user',
    type: 'provider_on_way',
    titleKa: 'ლევან წიკლაური გზაშია',
    messageKa: 'ოსტატი დაიძრა თქვენს მისამართზე (ი. ჭავჭავაძის 37).',
    deepLinkTab: 'tasks',
    taskId: 'task_active_ac',
    bookingId: 'bk_2026_ac_01',
    read: false,
    createdAt: '2026-09-04T13:55:00Z',
  },
  {
    id: 'notif_2',
    targetRole: 'user',
    type: 'quote_received',
    titleKa: 'შემოთავაზება მიღებულია',
    messageKa: 'ირაკლი კვარაცხელიამ გამოგიგზავნათ შეთავაზება: 85 ₾.',
    deepLinkTab: 'tasks',
    taskId: 'task_active_ac',
    read: false,
    createdAt: '2026-09-04T13:20:00Z',
  },
  {
    id: 'notif_3',
    targetRole: 'provider',
    type: 'new_match',
    titleKa: 'ახალი მოთხოვნა ვაკეში',
    messageKa: 'კონდიციონერის შემოწმება · დღეს 18:30 · 70–110 ₾.',
    deepLinkTab: 'requests',
    read: false,
    createdAt: '2026-09-04T13:15:00Z',
  },
];

export const seedActiveTasks: Task[] = [
  {
    id: 'task_active_ac',
    userId: 'usr_nukri',
    title: 'AC Repair & Inspection',
    titleKa: 'კონდიციონერის შემოწმება',
    rawPrompt: 'კონდიციონერი უცნაურ ხმას აკეთებს და არ აგრილებს',
    category: 'ac_heating',
    status: 'provider_on_way',
    urgency: 'high',
    location: 'ი. ჭავჭავაძის გამზ. 37, ვაკე',
    preferredTime: 'დღეს · 18:30',
    providerId: 'prov_levan_ac',
    estimatedPrice: {
      min: 70,
      max: 100,
      currency: '₾',
      marketStatus: 'normal_range',
      explanationText: 'საშუალო საბაზრო ფასის შესაბამისი',
    },
    aiSummary: 'AC diagnostic and antibacterial clean scheduled with Levan Tsiklauri.',
    aiSummaryKa: 'კონდიციონერის დიაგნოსტიკა და წმენდა დაგეგმილია ლევან წიკლაურთან.',
    recommendedProviderIds: ['prov_levan_ac', 'prov_irakli_ac'],
    timeSavedMinutes: 120,
    timeline: [
      {
        id: 'ev_1',
        time: '17:15',
        title: 'Request created',
        titleKa: 'მოთხოვნა შეიქმნა',
        description: 'AI analyzed audio note about AC noise',
        descriptionKa: 'DOXO-მ გააანალიზა მოთხოვნა კონდიციონერის შესახებ',
        actor: 'ai',
        statusAfter: 'analyzing',
      },
      {
        id: 'ev_2',
        time: '17:16',
        title: 'Levan matched & confirmed',
        titleKa: 'ლევან წიკლაური შეირჩა და დადასტურდა',
        actor: 'user',
        statusAfter: 'booked',
      },
      {
        id: 'ev_3',
        time: '17:55',
        title: 'Technician on the way',
        titleKa: 'ტექნიკოსი გზაშია',
        descriptionKa: 'პროვაიდერი დაიძრა მისამართზე (ვაკე)',
        actor: 'provider',
        statusAfter: 'provider_on_way',
      },
    ],
    createdAt: '2026-09-04T13:15:00Z',
    updatedAt: '2026-09-04T13:55:00Z',
  },
  {
    id: 'task_active_clean',
    userId: 'usr_nukri',
    title: 'Apartment Cleaning',
    titleKa: 'ბინის დალაგება',
    rawPrompt: 'ხვალ დილით ბინის დალაგება მინდა',
    category: 'cleaning',
    status: 'booked',
    urgency: 'medium',
    location: 'ი. ჭავჭავაძის გამზ. 37, ვაკე',
    preferredTime: 'ხვალ · 11:00',
    providerId: 'prov_nino_clean',
    estimatedPrice: {
      min: 80,
      max: 110,
      currency: '₾',
      marketStatus: 'normal_range',
      explanationText: 'სტანდარტული ტარიფი 3-ოთახიანი ბინისთვის',
    },
    aiSummary: 'Confirmed apartment cleaning with Nino Beridze.',
    aiSummaryKa: 'ბინის დალაგება დადასტურებულია ნინო ბერიძესთან.',
    recommendedProviderIds: ['prov_nino_clean', 'prov_mariam_clean'],
    timeSavedMinutes: 180,
    timeline: [
      {
        id: 'ev_c1',
        time: '14:20',
        title: 'Booking confirmed',
        titleKa: 'დაჯავშნა დადასტურებულია',
        descriptionKa: 'ნინო მოვა ხვალ 11:00-ზე',
        actor: 'user',
        statusAfter: 'booked',
      },
    ],
    createdAt: '2026-09-04T10:20:00Z',
    updatedAt: '2026-09-04T10:20:00Z',
  },
  {
    id: 'task_done_courier',
    userId: 'usr_nukri',
    title: 'Contract Delivery',
    titleKa: 'ნოტარიუსთან საბუთის მიტანა',
    rawPrompt: 'სასწრაფოდ წაუღე ხელშეკრულება ნოტარიუსს რუსთაველზე',
    category: 'courier',
    status: 'completed',
    urgency: 'urgent',
    location: 'რუსთაველის გამზ. 24, თბილისი',
    preferredTime: 'დღეს · 11:00',
    providerId: 'prov_salome_courier',
    estimatedPrice: {
      min: 25,
      max: 35,
      currency: '₾',
      marketStatus: 'normal_range',
      explanationText: 'ექსპრეს კურიერის ტარიფი',
    },
    finalPrice: 25,
    aiSummary: 'Contract securely hand-delivered to notary by Salome.',
    aiSummaryKa: 'სალომემ ხელშეკრულება პირადად ჩააბარა ნოტარიუსს 25 წუთში.',
    recommendedProviderIds: ['prov_salome_courier'],
    timeSavedMinutes: 60,
    review: {
      rating: 5,
      tags: ['დროული', 'სანდო', 'სწრაფი'],
      feedbackText: 'ზუსტად 25 წუთში ჩააბარა დოკუმენტი. საუკეთესო სერვისია!',
      createdAt: '2026-09-04T11:50:00Z',
    },
    timeline: [
      {
        id: 'ev_d1',
        time: '11:00',
        title: 'Pickup confirmed',
        titleKa: 'დოკუმენტი აღებულია',
        actor: 'provider',
        statusAfter: 'in_progress',
      },
      {
        id: 'ev_d2',
        time: '11:35',
        title: 'Delivered',
        titleKa: 'სამუშაო შესრულდა',
        descriptionKa: 'მიმღებმა ხელი მოაწერა მიღებას',
        actor: 'provider',
        statusAfter: 'completed',
      },
    ],
    createdAt: '2026-09-04T07:00:00Z',
    updatedAt: '2026-09-04T08:00:00Z',
  },
];

export const seedHomeProfile: HomeProfile = {
  id: 'home_vake',
  title: 'ვაკის ბინა',
  titleKa: 'ვაკის ბინა',
  address: 'ი. ჭავჭავაძის გამზ. 37, ბინა 18',
  district: 'ვაკე',
  roomsCount: 3,
  squareMeters: 92,
  appliances: [
    {
      id: 'app_ac_living',
      name: 'Samsung Inverter AC',
      nameKa: 'კონდიციონერი (მისაღები)',
      category: 'ac',
      brandModel: 'Samsung WindFree 18000 BTU',
      room: 'მისაღები ოთახი',
      roomKa: 'მისაღები ოთახი',
      lastServicedDate: '2026-03-12',
      suggestedNextServiceDate: '2026-09-15',
      maintenanceCycleMonths: 6,
      proactivePromptKa: 'კონდიციონერის ბოლო წმენდა 6 თვის წინ იყო. გინდა ამ კვირაში მოვძებნო ხელოსანი?',
      proactivePromptEn: 'AC was last cleaned 6 months ago. Shall I find a technician this week?',
      serviceNeeded: true,
    },
    {
      id: 'app_boiler',
      name: 'Ariston Heating Boiler',
      nameKa: 'ცენტრალური გათბობის ქვაბი',
      category: 'boiler',
      brandModel: 'Ariston Clas One 24kW',
      room: 'აივანი',
      roomKa: 'აივანი',
      lastServicedDate: '2025-11-20',
      suggestedNextServiceDate: '2026-10-15',
      maintenanceCycleMonths: 12,
      proactivePromptKa: 'ზამთრის სეზონამდე გათბობის ქვაბის წნევის შემოწმებაა რეკომენდებული.',
      proactivePromptEn: 'Pre-winter boiler pressure inspection recommended.',
      serviceNeeded: false,
    },
  ],
};

export const seedInboxItems: LifeInboxItem[] = [
  {
    id: 'inbox_magti_bill',
    title: 'Magti Internet Bill',
    titleKa: 'მაგთის ინტერნეტის გადასახადი',
    itemType: 'bill',
    rawContent: 'მაგთიკომი: თქვენი სააბონენტო დავალიანებაა 55.00₾. გადახდის ბოლო ვადაა ხვალ.',
    mediaUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=300&auto=format&fit=crop&q=80',
    aiInterpretation: {
      summary: 'Magti internet bill of 55₾ due tomorrow.',
      summaryKa: 'ეს ინტერნეტის გადასახადია (55₾) და ვადა ხვალ იწურება.',
      suggestedAction: 'create_reminder',
      deadline: 'ხვალ, 23:59',
      amount: 55,
      currency: '₾',
    },
    status: 'pending',
    createdAt: '2026-09-04T09:00:00Z',
  },
  {
    id: 'inbox_sink_photo',
    title: 'Bathroom Leak Photo',
    titleKa: 'ონკანის გაჟონვის ფოტო',
    itemType: 'photo',
    rawContent: 'ფოტო: აბაზანაში ნიჟარის ქვეშ მილიდან წყალი ჟონავს.',
    mediaUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=300&auto=format&fit=crop&q=80',
    aiInterpretation: {
      summary: 'Pipe leak detected under bathroom sink. Specialist required.',
      summaryKa: 'ნიჟარის ქვეშ შეერთების ადგილიდან წყალი ჟონავს. საჭიროა სანტექნიკოსი.',
      suggestedAction: 'schedule_service',
      categoryHint: 'plumbing',
    },
    status: 'pending',
    createdAt: '2026-09-04T08:30:00Z',
  },
];
